# Generated by Django 5.1.6 on 2025-02-20 03:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='no name', max_length=100)),
                ('last_name', models.CharField(default='no last name', max_length=100)),
                ('rut', models.CharField(default='no rut', max_length=12)),
                ('dob', models.DateField(default=datetime.date(1900, 1, 1))),
                ('chronic_diseases', models.JSONField(blank=True, default=dict, null=True)),
                ('predispositions', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_location', models.CharField(default='no wound location', max_length=100)),
                ('wound_origin', models.CharField(default='no wound cause', max_length=100)),
                ('wound_origin_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curametric_wound_api.patient')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wound',
                'verbose_name_plural': 'Wounds',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WoundCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_date', models.DateField(default=datetime.date(1900, 1, 1))),
                ('wound_heigh', models.FloatField(default=0)),
                ('wound_width', models.FloatField(default=0)),
                ('wound_depth', models.FloatField(default=0)),
                ('wound_necrotic_tissue', models.FloatField(default=0)),
                ('wound_sloughed_tissue', models.FloatField(default=0)),
                ('wound_granulation_tissue', models.FloatField(default=0)),
                ('wound_exudate_quantity', models.TextField(default='no exudate quantity')),
                ('wound_exudate_quality', models.TextField(default='no exudate quality')),
                ('wound_debridement', models.BooleanField(default=False)),
                ('wound_primary_dressing', models.TextField(default='no primary dressing')),
                ('wound_secondary_dressing', models.JSONField(blank=True, default=dict, null=True)),
                ('wound_next_care', models.DateField(default=datetime.date(1900, 1, 1))),
                ('wound_care_notes', models.TextField(default='no notes')),
                ('wound_photo', models.ImageField(blank=True, null=True, upload_to='wound_photos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wound_cares_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wound_cares_updated', to=settings.AUTH_USER_MODEL)),
                ('wound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curametric_wound_api.wound')),
            ],
            options={
                'verbose_name': 'Wound Care',
                'verbose_name_plural': 'Wound Cares',
                'ordering': ['created_at'],
            },
        ),
    ]
