# Generated by Django 5.1.6 on 2025-03-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curametric_wound_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woundcare',
            name='edema',
            field=models.TextField(blank=True, default='(-)', null=True),
        ),
        migrations.AddField(
            model_name='woundcare',
            name='skin_protection',
            field=models.TextField(default='no skin protection'),
        ),
        migrations.AddField(
            model_name='woundcare',
            name='surrounding_skin',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='woundcare',
            name='wound_cleaning_solution',
            field=models.TextField(default='no cleaning solution'),
        ),
        migrations.AddField(
            model_name='woundcare',
            name='wound_pain',
            field=models.TextField(blank=True, default='(-)', null=True),
        ),
    ]
