# Generated by Django 5.1.6 on 2025-03-16 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curametric_wound_api', '0002_woundcare_edema_woundcare_skin_protection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='woundcare',
            name='wound_ia_recomendation',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
